class_name StateManager extends Node

# Combat states
enum CombatState {
	EXPLORING,
	COMBAT_START,
	PLAYER_TURN,
	PLAYER_SELECTING_ENEMY,
	PLAYER_SELECTING_ATTACK,
	PLAYER_TIMED_EVENT,
	ENEMY_TURN,
	ENEMY_ATTACKING,
	PLAYER_DODGING,
	COMBAT_END
}
