extends Node

# Battle States
enum BattleState {
	START,
	PLAYER_TURN_START,
	PLAYER_SELECTING_ACTION,
	PLAYER_EXECUTING_ACTION,
	ENEMY_TURN_START,
	ENEMY_ATTACKING,
	PLAYER_DODGING,
	PROCESSING_RESULTS,
	WON,
	LOST
}
enum MenuState { ACTIVE, INACTIVE }

# Actions
enum PlayerAction { TONGUE_SLAP, TAIL_WHIP, RUN_AWAY }
enum EnemyAction { ATTACK, DEFEND, NOTHING }
